; Unified PHP settings for both CLI and FPM in official php-fpm image.
date.timezone=Europe/Moscow
display_errors=On
log_errors=On
error_reporting=E_ALL

; Maximum amount of memory a script may consume
memory_limit=512M
; Maximum allowed size for uploaded files
upload_max_filesize=64M
; Max size of post data
post_max_size=66M
max_execution_time=600

opcache.enable=1
opcache.enable_cli=0
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.memory_consumption=64
opcache.max_accelerated_files=100000
opcache.fast_shutdown=1
opcache.force_restart_timeout=60
opcache.file_update_protection=10

; JIT disabled for predictable behavior in mixed environments.
opcache.jit_buffer_size=0
opcache.jit=0

pcre.jit=0
realpath_cache_size=4096k
max_input_vars=10000
short_open_tag=On
session.gc_probability=1

; /usr/sbin/sendmail -t -i -f www@my.domain.com
sendmail_path=/usr/bin/msmtp -t -i
